### PR TITLE
Fixing azure pipelines for PR and branchs

### PR DESCRIPTION
**Pull request by fmrico**
Hi @esteve,

In azure-pipelines.yml there is a problem using curl. For example, in:

`curl -sk https://raw.githubusercontent.com/esteve/ros2_dotnet/%BUILD_SOURCEBRANCHNAME%/ament_dotnet_uwp.repos -o ament_dotnet_uwp.repos
`
- repo is fixed to `esteve`. If I make a PR, it will try to bring `ament_dotnet_uwp.repos` from a branch in `esteve`'s repo, instead of `fmrico`
- `BUILD_SOURCEBRANCHNAME` is also a problem. If I make a PR, this variable sets to `merge`.

After some other complex solutions, I found one that takes advantage of that all the code (PR or not) is copied into $(Build.Repository.LocalPath), so I suggest to use the  `ament_dotnet_uwp.repos` that exist in that directory. It is valid for any PR of any user, or a local commit, or a manual build.

Hope it helps !!!

### CODE REVIEW

**Comment by esteve** [comment]
@fmrico Thanks! However this does not seem to work as intended, the .repos file may point to different repositores other than the one that's fetched. For example, I may submit a pull request and the .repos file still points to master in one of the repositories.

**Comment by fmrico** [comment]
@esteve Yes, this fixes that the .repos is correct. That was the problem.

**Comment by esteve** [comment]
@fmrico I'm not following, could you elaborate your answer?

This change would use the URLs from the .repos file in the PR that's being submitted, so if it does not change the contents of the .repos file, the repositories that are imported by `vcs` may not correspond to the ones that should be tested on the CI.

**Comment by fmrico** [comment]
Hi @esteve,

I must apologize if I did not explain it correctly. I will try it again:

Let's think in a PR that changes `ros2_dotnet_uwp.repos` file in order to change a version of a repo, or a git URL. It is not a change in the code of ros2_dotnet, but in a version/repo of a dependency for building ros2_dotnet. 

Currently, this change will not take any effect, because in `azure-pipelines.yml` is hardcoded the `ros2_dotnet_uwp.repos` that the CI is going to use:

> curl -sk https://raw.githubusercontent.com/esteve/ros2_dotnet/%BUILD_SOURCEBRANCHNAME%/ament_dotnet_uwp.repos -o ament_dotnet_uwp.repos

CI should use the new/updated `ros2_dotnet_uwp.repos` that is contained in the PR. The address of the PR is not at `https://raw.githubusercontent.com/esteve/ros2_dotnet`, nor `%BUILD_SOURCEBRANCHNAME%` contains the branch name of the PR's branch (it contains `merge`).

Of course, if you merge the changes with a fail status in the CI, the next time you manually run CI, it will successfully build, but this is not correct. Any PR containing a change in `ros2_dotnet_uwp.repos` necessary to compile the PR will fail.

The change proposed in this PR let to use the `ros2_dotnet_uwp.repos` contained in the PR, because of CI first copy all the code of the PR in `$(Build.Repository.LocalPath)`. So, when you run `cvs import`, you are using the incoming `ros2_dotnet_uwp.repos` contained in the PR, as should be the case. 

> copy $(Build.Repository.LocalPath)\ament_dotnet_uwp.repos \dev\ament\ament_dotnet_uwp.repos
> vcs import src < ament_dotnet_uwp.repos

 Best

**Comment by esteve** [comment]
Thanks for the contribution. I ended up fixing the CI and also implementing what was missing in this pull request in https://github.com/esteve/ros2_dotnet/pull/30

**Pull request closed without merging**
